import { test, expect } from './fixtures'
test('create, edit, persist, complete and delete a task', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '新建任务', exact: true }).click()
  await page.getByLabel('准备做点什么？').fill('测试：整理书桌')
  await page.getByLabel('到期提醒时间').fill('')
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await page.getByRole('button', { name: /全部任务/ }).click()
  await page.getByRole('button', { name: '编辑：测试：整理书桌', exact: true }).click()
  await page.getByLabel('准备做点什么？').fill('测试：整理房间')
  await page.getByRole('button', { name: '保存修改' }).click()
  await page.reload()
  await page.getByRole('button', { name: /全部任务/ }).click()
  await expect(page.getByRole('button', { name: '测试：整理房间', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '完成：测试：整理房间', exact: true }).click()
  await expect(page.getByRole('button', { name: '取消完成：测试：整理房间', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '删除：测试：整理房间', exact: true }).click()
  await expect(page.getByRole('button', { name: '测试：整理房间', exact: true })).toHaveCount(0)
})
test('search and calendar filtering', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('搜索任务').fill('阅读')
  await expect(page.locator('.task-row')).toHaveCount(1)
  await page.getByLabel('搜索任务').fill('没有这个任务')
  await expect(page.getByText('没有找到匹配的任务')).toBeVisible()
  await page.getByLabel('搜索任务').fill('')
  await page.getByRole('button', { name: '下个月' }).click()
  await page.locator('.calendar-grid button').nth(15).click()
  await expect(page.locator('.task-row')).toHaveCount(0)
})
test('overdue reminders fire once and survive refresh', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '新建任务', exact: true }).click()
  await page.getByLabel('准备做点什么？').fill('到期提醒测试')
  await page.getByLabel('到期提醒时间').fill('2020-01-01T09:00')
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('到时间了：到期提醒测试')
  await page.getByRole('button', { name: '查看提醒', exact: true }).click()
  await expect(page.locator('.alert-entry')).toHaveCount(1)
  await page.reload()
  await page.waitForTimeout(1500)
  await page.getByRole('button', { name: '查看提醒', exact: true }).click()
  await expect(page.locator('.alert-entry')).toHaveCount(0)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('little-day-tasks-v1')!).find((t: {title: string}) => t.title === '到期提醒测试').reminded)).toBe(true)
})
test('desktop and mobile render without overflow or runtime errors', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.setViewportSize({ width: 1440, height: 1080 }); await page.goto('/')
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: '新建任务', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  expect(errors).toEqual([])
})
