import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.route('https://v1.hitokoto.cn/**', route => route.abort())
  await page.route('https://zh.wikipedia.org/**', route => route.fulfill({ json: { query: { search: [{ title: '参考资料' }] } } }))
})

test('first entry waits for preferences; settings can edit them from another task view', async ({ page }) => {
  const queries: string[] = []
  await page.route('https://zh.wikipedia.org/**', route => {
    queries.push(new URL(route.request().url()).searchParams.get('srsearch')!)
    return route.fulfill({ json: { query: { search: [{ title: '参考资料' }] } } })
  })
  await page.goto('/')
  const welcome = page.getByRole('dialog', { name: '先选兴趣，让小日更懂你' })
  await expect(welcome).toBeVisible()
  await expect(page.locator('#preference-heading')).toBeFocused()
  expect(queries).toHaveLength(0)
  await welcome.getByRole('group', { name: '学习成长', exact: true }).getByRole('radio', { name: '感兴趣', exact: true }).check()
  await welcome.getByRole('group', { name: '生活整理', exact: true }).getByRole('radio', { name: '不感兴趣', exact: true }).check()
  await welcome.getByRole('button', { name: '选好了，开始使用' }).click()
  await expect(welcome).not.toBeVisible()
  await expect(page.locator('.recommendation-summary')).toContainText('已联网')
  expect(queries).toHaveLength(3)
  expect(queries).not.toContain('整理收纳')
  const before = await page.evaluate(() => localStorage.getItem('little-day-preferences-v1'))
  await page.reload()
  await expect(page.locator('.recommendation-summary')).toContainText('已联网')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: /^全部任务/ }).click()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('dialog', { name: '设置', exact: true }).getByRole('button', { name: /推荐偏好/ }).click()
  const editor = page.getByRole('dialog', { name: '我的推荐偏好' })
  await expect(editor).toBeVisible()
  await editor.getByRole('group', { name: '学习成长', exact: true }).getByRole('radio', { name: '不感兴趣', exact: true }).check()
  await page.keyboard.press('Escape')
  expect(await page.evaluate(() => localStorage.getItem('little-day-preferences-v1'))).toBe(before)
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('dialog', { name: '设置', exact: true }).getByRole('button', { name: /推荐偏好/ }).click()
  await editor.getByRole('group', { name: '学习成长', exact: true }).getByRole('radio', { name: '不感兴趣', exact: true }).check()
  await editor.getByRole('button', { name: '保存推荐偏好' }).click()
  await page.getByRole('button', { name: /^今天/ }).click()
  await expect(page.locator('.recommendation-card')).toHaveCount(5)
  expect(await page.locator('.recommendation-meta > span:first-child').allTextContents()).not.toContain('学习成长')
  await page.reload()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(JSON.parse((await page.evaluate(() => localStorage.getItem('little-day-preferences-v1')))! ).areaAttitudes['学习成长']).toBe('excluded')
})

for (const dismissal of ['skip', 'escape', 'close']) test(`first-run ${dismissal} persists without saving draft choices`, async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-22T23:59:50') })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const welcome = page.getByRole('dialog', { name: '先选兴趣，让小日更懂你' })
  await expect(welcome).toBeVisible()
  await expect(welcome.getByRole('button', { name: '暂时跳过' })).toBeInViewport()
  await welcome.getByRole('group', { name: '学习成长', exact: true }).getByRole('radio', { name: '不感兴趣', exact: true }).check()
  if (dismissal === 'skip') {
    await welcome.screenshot({ path: 'test-results/onboarding-mobile.png' })
    expect(await welcome.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    await welcome.getByRole('button', { name: '暂时跳过' }).click()
  } else if (dismissal === 'escape') await page.keyboard.press('Escape')
  else await welcome.getByRole('button', { name: '关闭推荐偏好' }).click()
  await expect(welcome).not.toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('little-day-preferences-v1'))).toBeNull()
  expect(await page.evaluate(() => localStorage.getItem('little-day-recommendation-onboarding-v1'))).toBe('skipped')
  await page.reload()
  await expect(page.locator('.recommendation-card')).toHaveCount(5)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.clock.fastForward(20_000)
  await expect(page.locator('.recommendation-summary')).toContainText('09/23')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('existing saved preferences bypass onboarding and remain editable in settings', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('little-day-preferences-v1', JSON.stringify({ areas: ['学习成长'], interests: '摄影', count: 3, minutes: 30, online: false })))
  await page.goto('/')
  await expect(page.locator('.recommendation-card')).toHaveCount(8)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('dialog', { name: '设置', exact: true }).getByRole('button', { name: /推荐偏好/ }).click()
  await expect(page.getByRole('dialog', { name: '我的推荐偏好' })).toBeVisible()
  await expect(page.getByRole('group', { name: '学习成长', exact: true }).getByRole('radio', { name: '感兴趣', exact: true })).toBeChecked()
  await expect(page.getByRole('group', { name: '生活整理', exact: true }).getByRole('radio', { name: '不感兴趣', exact: true })).toBeChecked()
})

test('failed first-run save stays open and does not mark setup as complete', async ({ page }) => {
  await page.goto('/')
  const welcome = page.getByRole('dialog', { name: '先选兴趣，让小日更懂你' })
  await expect(welcome).toBeVisible()
  await page.evaluate(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function (key, value) {
      if (key === 'little-day-preferences-v1' || key === 'little-day-recommendation-onboarding-v1') throw Error('存储失败')
      original.call(this, key, value)
    }
  })
  await welcome.getByRole('button', { name: '选好了，开始使用' }).click()
  await expect(welcome.getByRole('alert')).toContainText('偏好保存失败')
  await expect(welcome).toBeVisible()
  await welcome.getByRole('button', { name: '暂时跳过' }).click()
  await expect(welcome.getByRole('alert')).toContainText('无法保存跳过状态')
  await expect(welcome).toBeVisible()
  await page.reload()
  await expect(welcome).toBeVisible()
})
