import { test, expect } from './fixtures'

test('choosing fewer candidates, adjusting a goal, editing later and next-day personalization', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-22T12:00:00') })
  await page.addInitScript(() => {
    if (!localStorage.getItem('little-day-preferences-v1')) localStorage.setItem('little-day-preferences-v1', JSON.stringify({ areaAttitudes: { 学习成长: 'excluded', 运动休息: 'interested', 生活整理: 'excluded', 人际连接: 'excluded', 兴趣创作: 'excluded', 自我回顾: 'excluded' }, interests: '', count: 10, minutes: 30, online: false }))
    if (!localStorage.getItem('little-day-tasks-v1')) localStorage.setItem('little-day-tasks-v1', '[]')
  })
  await page.route('https://v1.hitokoto.cn/**', route => route.abort())
  await page.goto('/')
  await expect(page.locator('.recommendation-card')).toHaveCount(10)
  expect(new Set(await page.locator('.recommendation-card h3').allTextContents()).size).toBe(10)
  await expect(page.locator('.task-row')).toHaveCount(0)
  const running = page.locator('.recommendation-card').filter({ has: page.getByRole('heading', { name: '轻松跑步 1 公里', exact: true }) })
  await running.getByRole('button', { name: '选择并调整' }).click()
  await page.getByLabel('目标量', { exact: true }).fill('0.5')
  await page.getByLabel('候选任务备注').fill('先试试半公里，保留自己的节奏。')
  await page.getByLabel('候选提醒时间').fill('')
  await page.getByRole('button', { name: '确认加入计划' }).click()
  await expect(running.getByRole('button', { name: '已在清单中' })).toBeDisabled()
  await expect(page.locator('.recommendation-summary')).toContainText('今天已选 1 个')
  await page.getByRole('button', { name: /^全部任务/ }).click()
  await expect(page.locator('.task-row')).toHaveCount(1)
  await page.getByRole('button', { name: '编辑：轻松跑步 0.5 公里', exact: true }).click()
  await page.getByLabel('编辑推荐目标', { exact: true }).fill('0.3')
  await page.getByRole('button', { name: '保存修改' }).click()
  await page.reload()
  await page.getByRole('button', { name: '选择与调整记录' }).click()
  const history = page.getByRole('dialog', { name: '选择与调整记录' })
  await expect(history).toContainText('原推荐：轻松跑步 1 公里')
  await expect(history).toContainText('首次接受：轻松跑步 0.5 公里')
  await expect(history).toContainText('当前计划：轻松跑步 0.3 公里')
  await page.getByRole('button', { name: '关闭选择记录' }).click()
  await page.clock.fastForward(24 * 60 * 60 * 1000)
  await expect(page.locator('.recommendation-card h3').first()).toHaveText('轻松跑步 0.3 公里')
  await expect(page.locator('.recommendation-reason').first()).toContainText('尚未完成时不增加目标')
  await page.locator('.recommendation-card').nth(1).getByRole('button', { name: '选择并调整' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('.candidate-dialog').screenshot({ path: 'test-results/choice-mobile.png' })
  expect(await page.locator('.candidate-dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.getByRole('button', { name: '再想想' }).click()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('little-day-tasks-v1')!).length)).toBe(1)
})
