import { test, expect } from './fixtures'

test.use({ timezoneId: 'Asia/Shanghai' })

test('create recurring task, complete, roll over, review and edit without duplicates', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-22T19:00:00+08:00'))
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('little-day-tasks-v1', '[]'))
  await page.reload()
  await page.getByRole('button', { name: '新建任务', exact: true }).click()
  await page.getByLabel('准备做点什么？').fill('每日英语')
  await page.getByLabel('重复周期').selectOption('daily')
  await page.getByLabel('每次提醒时间').fill('20:00')
  await page.getByLabel('每次目标时长').fill('30')
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await expect(page.locator('.task-row')).toHaveCount(1)
  await expect(page.locator('.task-row')).toContainText('每天 20:00 · 目标 30 分钟')
  await page.getByRole('button', { name: '开始：每日英语', exact: true }).click()
  await page.clock.setFixedTime(new Date('2026-09-22T19:30:00+08:00'))
  await page.getByRole('button', { name: '结束并完成：每日英语', exact: true }).click()
  await expect(page.locator('.task-row')).toHaveClass(/is-done/)
  await page.clock.setFixedTime(new Date('2026-09-23T19:00:00+08:00'))
  await expect(page.getByRole('button', { name: '开始：每日英语', exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: /全部任务/ }).click()
  await expect(page.locator('.task-row')).toHaveCount(1)
  await page.getByRole('button', { name: /时间回顾/ }).first().click()
  await page.getByLabel('回顾日期').fill('2026-09-22')
  await page.getByRole('button', { name: '查看记录：每日英语', exact: true }).click()
  await expect(page.locator('.record-detail')).toContainText('30 分钟')
  await page.getByRole('button', { name: /全部任务/ }).click()
  await page.getByRole('button', { name: '编辑：每日英语', exact: true }).click()
  await expect(page.getByLabel('重复周期')).toHaveValue('daily')
  await page.getByLabel('每次提醒时间').fill('21:00')
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(page.locator('.task-row')).toContainText('每天 21:00')
  await expect(page.locator('.task-row')).toHaveCount(1)
  await page.getByRole('button', { name: '2026-09-24', exact: true }).click()
  await expect(page.locator('.task-row')).toHaveCount(1)
  await page.getByRole('button', { name: '编辑：每日英语', exact: true }).click()
  await page.getByLabel('重复周期').selectOption('none')
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(page.locator('.task-row')).not.toContainText('每天')
})

test('weekly calendar shows only the scheduled weekdays and all tasks keeps one entry', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-22T19:00:00+08:00'))
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('little-day-tasks-v1', JSON.stringify([{ id: 'weekly', title: '周阅读', note: '', category: '个人', priority: '中', due: '2026-09-22T20:00', done: false, reminded: false, recurrence: { frequency: 'weekly', start: '2026-09-22', time: '20:00', records: {} } }])))
  await page.reload()
  await expect(page.locator('.task-row')).toContainText('每周二 20:00')
  await page.getByRole('button', { name: '2026-09-23', exact: true }).click()
  await expect(page.locator('.task-row')).toHaveCount(0)
  await page.getByRole('button', { name: '2026-09-29', exact: true }).click()
  await expect(page.locator('.task-row')).toHaveCount(1)
  await page.getByRole('button', { name: /全部任务/ }).click()
  await expect(page.locator('.task-row')).toHaveCount(1)
})
