import { test, expect } from './fixtures'

const task = (changes = {}) => ({ id: 'tracked', title: '阅读目标', note: '每天读一点', category: '课内', priority: '中', due: '2026-09-22T10:00', done: false, reminded: true, ...changes })
test.use({ timezoneId: 'Asia/Shanghai' })

test('start, reload, finish, review, export and reopen a task', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-22T09:00:00+08:00'))
  await page.goto('/')
  await page.evaluate(value => localStorage.setItem('little-day-tasks-v1', JSON.stringify(value)), [task()])
  await page.reload()
  await page.getByRole('button', { name: '开始：阅读目标', exact: true }).click()
  await expect(page.locator('.task-timing')).toContainText('09:00 — 进行中')
  await page.reload()
  await page.clock.setFixedTime(new Date('2026-09-22T09:30:00+08:00'))
  await expect(page.locator('.task-timing')).toContainText('30 分钟')
  await page.getByRole('button', { name: '结束并完成：阅读目标', exact: true }).click()
  await page.getByRole('button', { name: /时间回顾/ }).first().click()
  await page.getByRole('button', { name: '查看记录：阅读目标', exact: true }).click()
  await expect(page.locator('.record-detail')).toContainText('09:00 — 09:30 · 30 分钟')
  await expect(page.locator('.record-detail')).toContainText('原计划：2026-09-22 10:00')
  await expect(page.locator('.review-summary')).toContainText('当日完成 1 件')
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出任务', exact: true }).click()
  const download = await downloadEvent
  const stream = await download.createReadStream()
  const chunks = []
  for await (const chunk of stream!) chunks.push(chunk)
  const exported = JSON.parse(Buffer.concat(chunks).toString()).tasks[0]
  expect(exported.startedAt).toBe('2026-09-22T01:00:00.000Z')
  expect(exported.completedAt).toBe('2026-09-22T01:30:00.000Z')
  await page.reload()
  await page.getByRole('button', { name: /时间回顾/ }).first().click()
  await expect(page.locator('.execution-bar')).toHaveCount(1)
  await page.getByRole('button', { name: /全部任务/ }).click()
  await page.getByRole('button', { name: '取消完成：阅读目标', exact: true }).click()
  await expect(page.getByRole('button', { name: '开始：阅读目标', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /时间回顾/ }).first().click()
  await expect(page.locator('.execution-bar')).toHaveCount(0)
})

test('manual correction validates order and future times and splits a cross-midnight record', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-22T12:00:00+08:00'))
  await page.goto('/')
  await page.evaluate(value => localStorage.setItem('little-day-tasks-v1', JSON.stringify(value)), [task()])
  await page.reload()
  await page.getByRole('button', { name: '编辑：阅读目标', exact: true }).click()
  await page.getByText('实际执行时间 · 补录 / 修改', { exact: true }).click()
  await page.getByLabel('实际开始时间').fill('2026-09-21T23:30')
  await page.getByLabel('实际完成时间').fill('2026-09-21T23:00')
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.getByRole('alert')).toContainText('完成时间不能早于开始时间')
  await page.getByLabel('实际完成时间').fill('2026-09-23T00:30')
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.getByRole('alert')).toContainText('实际时间不能在未来')
  await page.getByLabel('实际完成时间').fill('2026-09-22T00:30')
  await page.getByRole('button', { name: '保存修改' }).click()
  await page.getByRole('button', { name: /时间回顾/ }).first().click()
  await page.getByRole('button', { name: '查看记录：阅读目标', exact: true }).click()
  await expect(page.locator('.timeline-time')).toContainText('2026-09-21 23:30 — 00:30 · 1 小时')
  await expect(page.locator('.review-summary')).toContainText('记录用时 30 分钟')
  await expect(page.locator('.review-summary')).toContainText('当日完成 1 件')
  await page.getByRole('button', { name: '回顾前一天' }).click()
  await expect(page.locator('.review-summary')).toContainText('记录用时 30 分钟')
  await expect(page.locator('.review-summary')).toContainText('当日完成 0 件')
  await page.getByRole('button', { name: '修改记录', exact: true }).click()
  await expect(page.getByLabel('实际开始时间')).toHaveValue('2026-09-21T23:30')
  await page.getByLabel('实际开始时间').fill('2026-09-21T23:00')
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.locator('.review-summary')).toContainText('记录用时 1 小时')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/time-review-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1080 })
  await page.screenshot({ path: 'test-results/time-review-desktop.png', fullPage: true })
})

test('review uses actual dates, retains ongoing tasks and excludes legacy completions', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-22T12:00:00+08:00'))
  await page.goto('/')
  await page.evaluate(value => localStorage.setItem('little-day-tasks-v1', JSON.stringify(value)), [
    task({ id: 'legacy', done: true }),
    task({ id: 'running', title: '跨天进行中', due: '', startedAt: '2026-09-21T15:00:00.000Z' }),
    task({ id: 'complete-only', title: '仅记录完成', due: '2026-09-20T10:00', done: true, completedAt: '2026-09-22T03:00:00.000Z' }),
  ])
  await page.reload()
  await page.getByRole('button', { name: /时间回顾/ }).first().click()
  await expect(page.locator('.execution-bar')).toHaveCount(2)
  await expect(page.locator('.execution-bar').first()).toHaveAttribute('aria-label', /跨天进行中/)
  await expect(page.locator('.execution-bar').last()).toHaveAttribute('aria-label', /未记录开始时间/)
  await expect(page.locator('.review-summary')).toContainText('记录用时 12 小时')
  await page.getByRole('button', { name: '回顾后一天' }).click()
  await expect(page.locator('.execution-bar')).toHaveCount(0)
  await page.getByLabel('回顾日期').fill('2026-09-21')
  await expect(page.locator('.execution-bar')).toHaveCount(1)
  await expect(page.locator('.review-summary')).toContainText('记录用时 1 小时')
})

test('task controls stay on the right below edit/delete and expose hover descriptions', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-22T12:00:00+08:00'))
  await page.goto('/')
  await page.evaluate(value => localStorage.setItem('little-day-tasks-v1', JSON.stringify(value)), [task()])
  await page.reload()
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1080 })
    const row = page.locator('.task-row')
    const action = row.getByRole('button', { name: '开始：阅读目标', exact: true })
    const edit = row.getByRole('button', { name: '编辑：阅读目标', exact: true })
    const remove = row.getByRole('button', { name: '删除：阅读目标', exact: true })
    await expect(edit).toHaveAttribute('title', '编辑：阅读目标')
    await expect(remove).toHaveAttribute('title', '删除：阅读目标')
    const [actionBox, editBox, removeBox, bodyBox] = await Promise.all([action.boundingBox(), edit.boundingBox(), remove.boundingBox(), row.locator('.task-body').boundingBox()])
    expect(actionBox!.y).toBeGreaterThanOrEqual(editBox!.y + editBox!.height)
    expect(actionBox!.x).toBeGreaterThanOrEqual(bodyBox!.x + bodyBox!.width)
    expect(editBox!.y).toBe(removeBox!.y)
    await page.screenshot({ path: `test-results/actions-${width}.png`, fullPage: true })
  }
  await page.getByRole('button', { name: '开始：阅读目标', exact: true }).click()
  await expect(page.locator('.row-actions .start-task')).toHaveText('结束并完成')
})

test('hourly chart scales and clips durations, separates overlaps and shows reminder points', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-22T18:00:00+08:00'))
  await page.goto('/')
  await page.evaluate(value => localStorage.setItem('little-day-tasks-v1', JSON.stringify(value)), [
    task({ id: 'overnight', title: '跨夜阅读', startedAt: new Date('2026-09-21T23:00:00+08:00').toISOString(), completedAt: new Date('2026-09-22T01:00:00+08:00').toISOString(), done: true, due: '' }),
    task({ id: 'morning', title: '课程学习', startedAt: new Date('2026-09-22T08:00:00+08:00').toISOString(), completedAt: new Date('2026-09-22T11:00:00+08:00').toISOString(), done: true }),
    task({ id: 'overlap', title: '听力练习', startedAt: new Date('2026-09-22T09:00:00+08:00').toISOString(), completedAt: new Date('2026-09-22T10:00:00+08:00').toISOString(), done: true, due: '2026-09-22T09:00' }),
    task({ id: 'point', title: '整理资料', completedAt: new Date('2026-09-22T12:00:00+08:00').toISOString(), done: true, due: '' }),
    task({ id: 'short', title: '快速记录', startedAt: new Date('2026-09-22T12:30:00+08:00').toISOString(), completedAt: new Date('2026-09-22T12:30:10+08:00').toISOString(), done: true, due: '' }),
    task({ id: 'running', title: '项目实践', startedAt: new Date('2026-09-22T14:00:00+08:00').toISOString(), due: '2026-09-22T17:00' }),
    task({ id: 'planned', title: '晚间复盘', due: '2026-09-22T21:00' }),
  ])
  await page.reload()
  await page.getByRole('button', { name: /时间回顾/ }).first().click()
  await page.setViewportSize({ width: 1440, height: 1080 })
  await expect(page.locator('.hour-axis>span')).toHaveCount(25)
  await expect(page.locator('.hour-axis>span').first()).toHaveText('00:00')
  await expect(page.locator('.hour-axis>span').last()).toHaveText('24:00')
  await expect(page.locator('.chart-row')).toHaveCount(7)
  await expect(page.locator('.execution-bar')).toHaveCount(6)
  const row = (title: string) => page.locator('.chart-row').filter({ has: page.getByRole('button', { name: `查看记录：${title}`, exact: true }) })
  const track = await row('课程学习').locator('.chart-track').boundingBox()
  const bar = await row('课程学习').locator('.execution-bar').boundingBox()
  expect((bar!.x - track!.x) / track!.width).toBeCloseTo(8 / 24, 2)
  expect(bar!.width / track!.width).toBeCloseTo(3 / 24, 2)
  const overnight = await row('跨夜阅读').locator('.execution-bar').boundingBox()
  expect(overnight!.x).toBeCloseTo(track!.x, 0)
  expect(overnight!.width / track!.width).toBeCloseTo(1 / 24, 2)
  await expect(row('整理资料').locator('.completion-point')).toHaveCount(1)
  await expect(row('晚间复盘').locator('.execution-bar')).toHaveCount(0)
  await expect(row('晚间复盘').locator('.planned-marker')).toHaveAttribute('title', /21:00/)
  await expect(row('项目实践').locator('.bar-running')).toHaveCount(1)
  await row('课程学习').locator('.execution-bar').click()
  await expect(page.getByRole('region', { name: '任务时间详情' })).toContainText('08:00 — 11:00 · 3 小时')
  await page.screenshot({ path: 'test-results/hourly-chart-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const scroll = page.getByRole('region', { name: '全天任务时间轴', exact: true })
  await row('晚间复盘').locator('.chart-task').scrollIntoViewIfNeeded()
  await scroll.evaluate(element => { element.scrollLeft = element.scrollWidth })
  await expect(row('晚间复盘').locator('.planned-marker')).toBeInViewport()
  await expect(row('晚间复盘').locator('.chart-task')).toBeInViewport()
  await page.screenshot({ path: 'test-results/hourly-chart-mobile.png', fullPage: true })
  await row('晚间复盘').locator('.planned-marker').click()
  await expect(page.getByRole('region', { name: '任务时间详情' })).toContainText('尚未记录执行时间')
})
