import { test, expect } from './fixtures'

test('legacy categories migrate without losing tasks', async ({ page }) => {
  await page.addInitScript(() => {
    if (!localStorage.getItem('little-day-tasks-v1')) localStorage.setItem('little-day-tasks-v1', JSON.stringify(['工作', '学习'].map((category, i) => ({id: String(i), title: `原有任务${i}`, note: '保留备注', category, priority: '高', due: '', done: false, reminded: false}))))
  })
  await page.goto('/')
  await page.getByRole('button', { name: /^课外/ }).click()
  await expect(page.locator('.task-name')).toHaveText('原有任务0')
  await page.getByRole('button', { name: /^课内/ }).click()
  await expect(page.locator('.task-name')).toHaveText('原有任务1')
  await page.reload()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('little-day-tasks-v1')!).map((task: {category: string}) => task.category))).toEqual(['课外', '课内'])
})

test('manual date preserves raw digits, validates and normalizes at confirmation', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '新建任务', exact: true }).click()
  await page.getByLabel('准备做点什么？').fill('手动时间测试')
  await page.getByRole('button', { name: '✎ 手动输入' }).click()
  await page.getByLabel('提醒年', { exact: true }).fill('2028')
  await page.getByLabel('提醒月', { exact: true }).fill('2')
  await page.getByLabel('提醒日', { exact: true }).fill('30')
  await page.getByLabel('提醒时', { exact: true }).fill('9')
  await page.getByLabel('提醒分', { exact: true }).fill('5')
  await expect(page.getByLabel('提醒月', { exact: true })).toHaveValue('2')
  await expect(page.getByLabel('提醒时', { exact: true })).toHaveValue('9')
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('不存在')
  await page.getByLabel('提醒日', { exact: true }).fill('29')
  await page.getByRole('button', { name: '确认时间', exact: true }).click()
  await expect(page.getByLabel('提醒月', { exact: true })).toHaveValue('02')
  await expect(page.locator('.time-summary')).toContainText('2028-02-29 09:05')
  await page.getByLabel('提醒年', { exact: true }).fill('202')
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('年份为 4 位')
  await page.getByLabel('提醒年', { exact: true }).fill('2028')
  await page.getByLabel('提醒日', { exact: true }).fill('8')
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('little-day-tasks-v1')!).find((task: {title: string}) => task.title === '手动时间测试').due)).toBe('2028-02-08T09:05')
})

test('quote is cached within a day and changes across midnight', async ({ page }) => {
  let requests = 0
  await page.clock.install({ time: new Date('2026-09-22T23:59:50') })
  await page.route('https://v1.hitokoto.cn/**', async route => { requests++; await route.fulfill({ json: { hitokoto: requests === 1 ? '坚持每一小步，让努力成为明天的底气。' : '相信自己的努力，勇敢迎接新的开始。', from: '测试语录' } }) })
  await page.goto('/')
  await expect(page.locator('.daily-quote strong')).toHaveText('坚持每一小步，让努力成为明天的底气。')
  expect(requests).toBe(1)
  await page.reload()
  await expect(page.locator('.daily-quote strong')).toHaveText('坚持每一小步，让努力成为明天的底气。')
  expect(requests).toBe(1)
  await page.clock.fastForward(20_000)
  await expect(page.locator('.daily-quote strong')).toHaveText('相信自己的努力，勇敢迎接新的开始。')
  expect(requests).toBe(2)
})

test('offline fallback changes daily and mobile manual editor fits', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-22T23:59:50') })
  await page.route('https://v1.hitokoto.cn/**', route => route.abort())
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.daily-quote')).toContainText('小日精选')
  const first = await page.locator('.daily-quote strong').textContent()
  await page.clock.fastForward(20_000)
  await expect(page.locator('.daily-quote strong')).not.toHaveText(first!)
  await page.getByRole('button', { name: '新建任务', exact: true }).click()
  await page.getByRole('button', { name: '✎ 手动输入' }).click()
  await page.getByRole('button', { name: '不设提醒' }).click()
  await expect(page.getByLabel('提醒年', { exact: true })).toHaveValue('')
  await page.screenshot({ path: 'test-results/manual-mobile.png', fullPage: true })
  expect(await page.getByRole('dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
})
